sources:
  - name: kress
    domain: kress.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://kress.de/news
      - https://kress.de/suche
  - name: turi2
    domain: turi2.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://turi2.de/aktuell/
      - https://turi2.de/tag/personalien/
  - name: MEEDIA
    domain: meedia.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://meedia.de/
      - https://meedia.de/news/
