sources:
  - name: kress
    domain: kress.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://kress.de/news
      - https://kress.de/suche
  - name: turi2
    domain: turi2.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://turi2.de/aktuell/
      - https://turi2.de/tag/personalien/
  - name: MEEDIA
    domain: meedia.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://meedia.de/
      - https://meedia.de/news/
  - name: newsroom.de
    domain: newsroom.de
    trust: mittel
    source_priority: mittel
    target_pages:
      - https://www.newsroom.de/
      - https://www.newsroom.de/news/
  - name: journalist.de
    domain: journalist.de
    trust: hoch
    source_priority: hoch
    target_pages:
      - https://www.journalist.de/
      - https://www.journalist.de/startseite/meldungen
  - name: journa.host
    domain: journa.host
    trust: niedrig
    source_priority: niedrig
    target_pages:
      - https://journa.host/public/local
